# Generated by Django 5.2 on 2025-07-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_tarifa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='tarifas/'),
        ),
    ]
