# Generated by Django 5.1.4 on 2025-02-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('creacion', 'Creación'), ('modificacion', 'Modificación'), ('eliminacion', 'Eliminación'), ('cambio_estado', 'Cambio de Estado')], max_length=50)),
                ('descripcion', models.TextField()),
                ('usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
