# Generated by Django 5.1.4 on 2025-02-03 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_registroevento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroEvento',
        ),
    ]
