# Generated by Django 5.1.4 on 2025-02-08 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_delete_registroevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='servicio_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TrabajadorAsignado', to='orders.reserva'),
        ),
    ]
