# Generated by Django 5.1.4 on 2025-02-08 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_reserva_servicio_actual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='servicio_actual',
        ),
    ]
