# Generated by Django 5.1.4 on 2025-02-08 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_reserva_servicio_actual'),
        ('workers', '0003_alter_worker_servicio_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='workers.worker'),
        ),
    ]
