# Generated by Django 5.1.4 on 2025-02-08 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_delete_registroevento'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='estado',
            field=models.CharField(choices=[('conectado', 'Conectado'), ('ausente', 'Ausente'), ('ocupado', 'Ocupado'), ('desconectado', 'Desconectado')], default='desconectado', max_length=15),
        ),
        migrations.AlterField(
            model_name='worker',
            name='servicio_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_asignado', to='orders.reserva'),
        ),
    ]
