# Generated by Django 5.1.4 on 2025-02-08 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_reserva_servicio_actual'),
        ('workers', '0002_alter_worker_estado_alter_worker_servicio_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='servicio_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workerAsignado', to='orders.reserva'),
        ),
    ]
