# Generated by Django 5.1.4 on 2025-02-08 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_create_worker_group'),
        ('workers', '0003_alter_worker_servicio_actual'),
    ]

    operations = [
    ]
