# Generated by Django 5.1.4 on 2025-02-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_merge_20250208_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='servicio_activo',
            field=models.BooleanField(default=False),
        ),
    ]
