# Generated by Django 5.1.4 on 2025-02-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_worker_servicio_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='servicio_activo',
        ),
        migrations.AlterField(
            model_name='worker',
            name='estado',
            field=models.CharField(choices=[('conectado', 'Conectado'), ('ausente', 'Ausente'), ('ocupado', 'Ocupado'), ('desconectado', 'Desconectado'), ('hora de comida', 'Hora de Comida')], default='desconectado', max_length=15),
        ),
    ]
