# Generated by Django 5.1.4 on 2025-02-12 10:47

import workers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0006_remove_worker_servicio_activo_alter_worker_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=workers.models.Worker.custom_upload_to),
        ),
    ]
