# Generated by Django 5.1.4 on 2025-02-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0007_worker_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
